// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package io.grpc.justtest;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:onlytest.TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
